
import java.awt.Color;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Danilo_Oliveira
 */
public class TelaIni extends javax.swing.JFrame {

    String nome;
//    ChatUI chat = new ChatUI();

    /**
     * Creates new form Tela
     */
    public TelaIni() {
        initComponents();
        tx.setBackground(new Color(129, 184, 211));
        tf.setVisible(false);
        btEnviar.setVisible(false);

    }
//     public Tela(String nome) {
//        initComponents();
//        this.nome = nome;    
//      
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        lbIcon = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btConversar = new javax.swing.JButton();
        tf = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tx = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(129, 184, 211));

        lst.setBackground(new java.awt.Color(129, 184, 211));
        lst.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lst.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        lst.setForeground(new java.awt.Color(242, 238, 238));
        jScrollPane2.setViewportView(lst);

        jPanel4.setBackground(new java.awt.Color(63, 59, 113));

        lbIcon.setForeground(new java.awt.Color(254, 254, 254));
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userP.png"))); // NOI18N

        lbPerfil.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        lbPerfil.setForeground(new java.awt.Color(254, 254, 254));
        lbPerfil.setText("Welcome to chat");

        lbNome.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lbNome.setForeground(new java.awt.Color(254, 254, 254));
        lbNome.setText("NOME");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNome))
                    .addComponent(lbPerfil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNome)
                        .addGap(18, 18, 18)))
                .addComponent(lbPerfil)
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(254, 254, 254));
        jSeparator1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N

        btConversar.setText("Conversar");
        btConversar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConversarActionPerformed(evt);
            }
        });

        btEnviar.setText("enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(129, 184, 211));

        tx.setEditable(false);
        tx.setBackground(new java.awt.Color(129, 184, 211));
        tx.setColumns(20);
        tx.setRows(5);
        jScrollPane3.setViewportView(tx);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConversar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEnviar)
                    .addComponent(btConversar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Help");
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Perfil");

        jMenuItem3.setText("Editar perfil");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String nome = lbNome.getText();
        if (doConnect(nome) == false) {
            try {
                server.sair(nome);
                this.dispose();
            } catch (RemoteException ex) {
                System.err.println("Erro ao sair\n" + ex);
            }

        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btConversarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConversarActionPerformed
        // TODO add your handling code here:
        if (btConversar.getText().equals("Conversar")) {
            btConversar.setText("voltar");
            tx.setBackground(Color.WHITE);
            tf.setVisible(true);
            btEnviar.setVisible(true);
            lst.setForeground(new Color(129, 184, 211));            
//            Tela t = new Tela(lbNome.getText());
//            t.show();

        }
        else {
            btConversar.setText("Conversar");
            tx.setBackground(new Color(129, 184, 211));
            tf.setVisible(false);
            btEnviar.setVisible(false);
            lst.setForeground(new Color(254, 254, 254)); 
            
        }
        //this.dispose();
    }//GEN-LAST:event_btConversarActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String texto = tf.getText();
        TelaLogin tl = new TelaLogin();
        if (!texto.isEmpty()) {
            
            if(lst.getSelectedValue()!=null){
                sendText(lst.getSelectedValue());
                System.out.println("vou mandar para "+lst.getSelectedValue());
            }
            else{
                sendText();
            }
         
          
        }
    }//GEN-LAST:event_btEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    JFrame frame;
    private ChatClient client;
    private ChatServerInt server;
    private String nomeTelaLogin;
    public boolean conectado = false;

//    public boolean doConnect(String nome) {
//        nomeTelaLogin = nome;
//        //int listaClientes;
////        try {
//        //FDP TA COMENTADO PQ TA RENORNADO NULO
//        // List<ChatClientInt> clientes =  (List<ChatClientInt>) server.getConnected();
//        //Percorre a lista de clientes 
////            if(clientes.size()>0){
////                listaClientes = server.getConnected().size();
////                for (int i = 0; i < listaClientes; i++) {
////                    //verifica se o novo cliente tem o mesmo nome
////                    if (clientes.get(i).getName().equals(nome)) {
////                        //se houver um clinete com o mesmo nome informa a msg 
////                        JOptionPane.showMessageDialog(null, "Já exite um Cliente com esse nome");
////                        break;
////                    } 
////                 }
////            }
////                //senao houver clinte com o mesmo nome
////                else {
//        //verifica se cliente ta conectado
//        if (conectado == false) {
//            //se nao tiver conectado
//            try {
//                client = new ChatClient(nome);
//                //client.setGUI(this);
//                // server=(ChatServerInt)Naming.lookup("rmi://"+ip.getText()+"/myabc");
//                server = (ChatServerInt) Naming.lookup("rmi://localhost/myabc");
//                server.login(client);
//                updateUsers(server.getConnected());
//                conectado = true;
//                lbNome.setText(nome);
//            } catch (Exception e) {
//                e.printStackTrace();
//                JOptionPane.showMessageDialog(frame, "ERROR, we wouldn't connect....");
//            }
//        } //senao se cliente ja tiver conectado
//        else {
//            updateUsers(null);
//            conectado = false;
//        }
////                }
////
//////            }
////        catch (RemoteException ex) {
////            System.err.println("Erro ao conectar"+ex.getMessage());
////        }
//
//        return conectado;
//    }
    public boolean doConnect(String nome) {
        if (conectado==false) {
            try {
                client = new ChatClient(nome);
                client.setGUI(this);
//    		server=(ChatServerInt)Naming.lookup("rmi://"+ip.getText()+"/myabc");
                server = (ChatServerInt) Naming.lookup("rmi://localhost/myabc");
                server.login(client);
                updateUsers(server.getConnected());
                conectado = true;
                lbNome.setText(nome);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(frame, "ERROR, we wouldn't connect....");
            }
        } 
        else {
            updateUsers(null);
            conectado = false;
        }
        return conectado;
    }
    public void sendText() {
        if (conectado==false) {
            JOptionPane.showMessageDialog(frame, "You need to connect first.");           
        }
        String st = tf.getText();
        st = "[" + lbNome.getText()+ "] " + st;
        tf.setText("");
        //Remove if you are going to implement for remote invocation
        try {
            server.publish(st);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void sendText(String nome) {
        if (conectado==false) {
            JOptionPane.showMessageDialog(frame, "You need to connect first.");           
        }
        String st = tf.getText();
        st = "[" + lbNome.getText()+ "] " + st;
        tf.setText("");
        //Remove if you are going to implement for remote invocation
        try {
            server.publish(nome,st);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void writeMsg(String st) {
        tx.setText(tx.getText() + "\n" + st);
    }

    public void updateUsers(List<ChatClientInt> v) {
        DefaultListModel listModel = new DefaultListModel();
        if (v != null) {
            for (int i = 0; i < v.size(); i++) {
                try {
                    String tmp = ((ChatClientInt) v.get(i)).getName();
                    listModel.addElement(tmp);
                } catch (Exception e) {
                    e.printStackTrace();
                } 
                lst.setModel(listModel);
            }
        }
       
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConversar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JList<String> lst;
    private javax.swing.JTextField tf;
    private javax.swing.JTextArea tx;
    // End of variables declaration//GEN-END:variables
}
